parameters:
    spipu.core.encryptor.key_pair: '%env(resolve:APP_ENCRYPTOR_KEY_PAIR)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $logsDir: '%kernel.logs_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Spipu Core Environment
    Spipu\CoreBundle\Service\Environment:
        arguments:
            $currentCode: '%env(APP_ENV)%'

    # App Menu Definition
    spipu.ui.service.menu_definition:
        class: 'App\Service\MenuDefinition'
        autowire: true

    # Spipu User Bundle Configuration
    Spipu\UserBundle\Service\ModuleConfigurationInterface:
        class: Spipu\UserBundle\Service\ModuleConfiguration
        public: true
        arguments:
            $entityName:      'App\Entity\User'
            $entityClassName: '\App\Entity\User'
            $allowAccountCreation: false
            $allowPasswordRecovery: true

    # Process Steps
    App\Step\:
        resource: '../src/Step/*'
        tags: ['spipu.process.step']
        public: true
        autowire: true

    # Dashboard Widgets
    App\WidgetSource\:
        resource: '../src/WidgetSource/*'
        tags: ['spipu.widget.source']
        autowire: true
